[workspace]
members = ["server"]
resolver = "2"
# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
# object_store added support for SSE-C headers in:
# - https://github.com/apache/arrow-rs/pull/6230
# - https://github.com/apache/arrow-rs/pull/6260
# But a new version hasn't been published to crates.io for this yet. So, we are using this patch temporarily.
object_store = { git = "https://github.com/apache/arrow-rs.git", rev = "23b6ff9f432e8e29c08d47a315ba0b7cb8758225" }
